### ISSUE TITLE
problem: the ceph credentials are readable in the userapi for any volumerequest

### ISSUE THREAD

**Issue by gehoern** [onmetal/cephlet#127]
we generate ceph credentials in the storage cluster -> partitionlet syncs them uphill because we need to provide them to hardware / virtual machine providers.

Problem:
- we currently have not a different credential for every disk
- we expose internal structures -> ceph monitor address is contained
- and it is not usable for a customer at all (does not need to know)

probable solution could be:
- to stop secret propagation at the region level
- just adding an RBAC rule is simple but still exposes internal data to the userAPI (needless for customers)
 
keep in mind:
- ceph clusters can be distributed over a region for latency reasons (region <2ms latency - is fine for ceph) 
- multi region setups always involve multiple clusters = anyhow different credentials

**Comment by lukasfrank** [comment]
Closing this issue in favour of the issue https://github.com/onmetal/onmetal-api/issues/567 in the `onmetal-api`
