### ISSUE TITLE
right security separation data and key

### ISSUE THREAD

**Issue by ubi2go** [onmetal/cephlet#173]
# Summary

integrate encrypted images with external key

## Basic example

kubernetes secret to store the key of each image separated from the rbd image (pvc)
add the rbd image(pvc) and the key to the libvirt definition.

## Motivation

right security separation and also deny the access to different images by incident.

https://libvirt.org/formatstorageencryption.html#luks2-format
https://docs.ceph.com/en/quincy/rbd/rbd-encryption/
https://pkg.go.dev/github.com/ceph/go-ceph/rbd#EncryptionOptionsLUKS2
https://github.com/ceph/ceph-csi/blob/53bb28e0d9e368f09e74494804e9c577285e4d6b/internal/util/crypto.go
https://github.com/ceph/ceph-csi/blob/53bb28e0d9e368f09e74494804e9c577285e4d6b/internal/util/cryptsetup.go

**Comment by lukasfrank** [comment]
Will be addressed in issue #187
