### ISSUE TITLE
Stream data to block device instead of copying the artefacts 

### ISSUE THREAD

**Issue by afritzler** [onmetal/cephlet#45]
# Summary

Currently we are copying the OCI image artefacts into the populator pod before writing them to the block device. This might cause a problem if the OCI image is to large and might cause to `Pod` to run out of disk space.

## Proposed solution

Use `io.Reader`/`io.Writer` to stream the content from the remote location directly to the block device.

**Comment by lukasfrank** [comment]
If the sink and the source implement the Reader/Writer interface `io.Copy` is "streaming" the data: 
https://pkg.go.dev/io#Copy 
I think there is no need to change.

**Comment by afritzler** [comment]
Not quite: we are pulling the image artefacts first here https://github.com/onmetal/cephlet/blob/main/cmd/populator/populator.go#L67

The content of https://github.com/onmetal/cephlet/blob/main/cmd/populator/populator.go#L73 should be streamed from the OCI repository directly.

**Comment by lukasfrank** [comment]
ah, now I got your point! Was confused because of the comment in the code :)

**Comment by afritzler** [comment]
Yeah, the TODO was placed in the wrong location. :)
